AllCops:
  Exclude:
    - "**/vendor/**/*"
    - "**/*.gemspec"
    - "spec/**"
  NewCops: enable
  TargetRubyVersion: 2.6
  SuggestExtensions: false

Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: true
Style/AsciiComments:
  Enabled: false  
Layout/LineLength:
  Max: 120
